Models/Actor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ActorsApp.Models
{
    public class Actor
    
    {
        public int Id{get; set;}
        public string StageName{get; set;}

        public string FirstName{get; set;}

        public string LastName{get; set;}

        public int Age{get; set;}

        public string Image{get; set;}

        public string Description{get; set;}

        public string BestMovie{get; set;}
    }
}

Models/ErrorViewModel.cs
namespace ActorsApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ActorsApp.Models;
using ActorsApp.Services;

namespace ActorsApp.Controllers
{
    [Route("[controller]")]
    public class ActorsController : Controller
    {
       InMemomryActorsService _service ;
       public ActorsController(){
        _service = new InMemomryActorsService();
       }

       public IActionResult Index(){
        List<Actor> actors = _service.GetAllActors();
        return View(actors);
       }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ActorsApp.Models;

namespace ActorsApp.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Actors/index.cshtml
@model IEnumerable<Actor>


@* <table class = "table">
    <thead>
        <tr>
            <th scope = "col">Id</th>
            <th scope = "col">StageName</th>
            <th scope = "col">FirstName</th>
            <th scope = "col">LastName</th>
            <th scope = "col">Age</th>
            <th scope = "col">Image</th>
            <th scope = "col">Description</th>
            <th scope = "col">BestMovie</th>
            
            
        </tr>
    </thead>
    <tbody>
        @foreach (var actor in Model){
            <tr>
                <th scope="row">@actor.Id</th>
                <td>@actor.StageName</td>
                <td>@actor.FirstName</td>
                <td>@actor.LastName</td>
                <td>@actor.Age</td>
                <td>@actor.Image</td>
                <td>@actor.Description</td>
                <td>@actor.BestMovie</td>
            </tr>
        }
        
            
        
    </tbody>
</table> *@


<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.StageName
                                    
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.Image" width="100%" alt="@item.StageName">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>First Name : </b>@item.FirstName</p>
                            <p class="card-text"><b>Last Name: </b>@item.LastName</p>
                            <p class="card-text"><b>Age : </b>@item.Age</p>
                            <p class="card-text"><b>Best Movie: </b>@item.BestMovie</p>
                            

                        </div>
                    </div>
                    </div>
                </div>
            </div>
        
    }
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-Left">
    <h1 class="display-3">Welcome To BhaiVerse</h1>
    <p> Here You will learn about the Bhai of Indian Cinema </p>
    <h2>Sallu Bhai</h2>
     <img src = "https://th.bing.com/th/id/OIP.zAFHDGzzd7NfhYQKEVK1sAHaD8?w=340&h=181&c=7&r=0&o=5&dpr=1.5&pid=1.7"> 
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ActorsApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ActorsApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ActorsApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class = "nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actors" asp-action="Index">Actors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ActorsApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>